### ISSUE TITLE
Fortran compiler found

### ISSUE THREAD

**Issue by kevinmcalear** [thenovices/heroku-buildpack-scipy#4]
I have been trying to use this tool and it seems awesome! Thanks for making it!  :+1:  But at the very end of running:

      git push heroku master 

and installing everything I get this:

       building 'dfftpack' library

             error: library dfftpack has Fortran sources but no Fortran compiler found

Any thoughts on why that would be missing?

**Comment by DaveX101** [comment]
I'm getting this same error here. I believe the problem is that despite including scipy==0.15.1 in my requirements file, and the build pack downloading the pre built version of this -- my build process is still attempting to compile scipy from scratch. (It **does** need that Fortran compiler so I'm not sure how you got around that problem by just re-ordering your requirements). 

Thanks for keeping this build pack up-to-date. It's helped me a lot, I'm hoping to figure out this small hurdle. @kevinmcalear Thanks in advance. 

```
numpy==1.9.2
scipy==0.15.1
appnope==0.1.0
blessings==1.6
colour-runner==0.0.4
CVXcanon==0.0.17
cvxopt==1.1.7
cvxpy==0.3.0
decorator==4.0.2
dj-database-url==0.3.0
dj-static==0.0.6
Django==1.8.4
django-toolbelt==0.0.1
djangorestframework==3.2.3
ecos==2.0.4
geopy==1.11.0
gnureadline==6.3.3
gunicorn==19.3.0
ipdb==0.8.1
ipython==4.0.0
ipython-genutils==0.1.0
matplotlib==1.4.3
nose==1.3.7
pandas==0.16.2
path.py==8.1.1
pep8==1.6.2
pexpect==3.3
pickleshare==0.5
psycopg2==2.6.1
Pygments==2.0.2
pyparsing==2.0.3
python-dateutil==2.4.2
pytz==2015.4
requests==2.7.0
scikit-learn==0.16.1
scs==1.1.4
simplegeneric==0.8.1
six==1.9.0
sklearn==0.0
static3==0.6.1
termcolor==1.1.0
toolz==0.7.4
traitlets==4.0.0
```

**Comment by thenovices** [comment]
What version of python are you using? This project only works for Python 2.7 right now.

**Comment by DaveX101** [comment]
Sorry man, did not read the fine print. I'm on Python 3.4 so of course it's not working. Support for 3 would be amazing for this build pack. We just put in a big effort to port our big scientific application to 3 and were hoping to put it up on Heroku. Anyways, I'll figure something out. Thanks

**Comment by thenovices** [comment]
Yeah I should make that clearer. I haven't gotten around to adding support for Python 3 yet. There's some discussion here about it thought: https://github.com/thenovices/heroku-buildpack-scipy/issues/14
